version: "3.9"
services:
  database:
    image: mysql:8.0
    container_name: database_bank_go
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bank
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
volumes:
  go-data: